package ec.edu.yavirac.instituto.modelo;
// Generated Sep 14, 2017 9:17:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private Integer idActividad;
     private Fase fase;
     private Date fechaCreate;
     private String tarea;
     private String meta;
     private String observacion;
     private Integer flag;
     private Set evaluacions = new HashSet(0);
     private Set evidencias = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(Fase fase) {
        this.fase = fase;
    }
    public Actividad(Fase fase, Date fechaCreate, String tarea, String meta, String observacion, Integer flag, Set evaluacions, Set evidencias) {
       this.fase = fase;
       this.fechaCreate = fechaCreate;
       this.tarea = tarea;
       this.meta = meta;
       this.observacion = observacion;
       this.flag = flag;
       this.evaluacions = evaluacions;
       this.evidencias = evidencias;
    }
   
    public Integer getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(Integer idActividad) {
        this.idActividad = idActividad;
    }
    public Fase getFase() {
        return this.fase;
    }
    
    public void setFase(Fase fase) {
        this.fase = fase;
    }
    public Date getFechaCreate() {
        return this.fechaCreate;
    }
    
    public void setFechaCreate(Date fechaCreate) {
        this.fechaCreate = fechaCreate;
    }
    public String getTarea() {
        return this.tarea;
    }
    
    public void setTarea(String tarea) {
        this.tarea = tarea;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }
    public Set getEvidencias() {
        return this.evidencias;
    }
    
    public void setEvidencias(Set evidencias) {
        this.evidencias = evidencias;
    }




}


