package ec.edu.yavirac.instituto.modelo;
// Generated Sep 14, 2017 9:17:28 AM by Hibernate Tools 4.3.1



/**
 * Evidencia generated by hbm2java
 */
public class Evidencia  implements java.io.Serializable {


     private int idEvidencia;
     private Actividad actividad;
     private Usuario usuario;
     private byte[] pdf;
     private byte[] video;
     private byte[] foto;
     private Integer flag;

    public Evidencia() {
    }

	
    public Evidencia(int idEvidencia, Actividad actividad, Usuario usuario) {
        this.idEvidencia = idEvidencia;
        this.actividad = actividad;
        this.usuario = usuario;
    }
    public Evidencia(int idEvidencia, Actividad actividad, Usuario usuario, byte[] pdf, byte[] video, byte[] foto, Integer flag) {
       this.idEvidencia = idEvidencia;
       this.actividad = actividad;
       this.usuario = usuario;
       this.pdf = pdf;
       this.video = video;
       this.foto = foto;
       this.flag = flag;
    }
   
    public int getIdEvidencia() {
        return this.idEvidencia;
    }
    
    public void setIdEvidencia(int idEvidencia) {
        this.idEvidencia = idEvidencia;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public byte[] getPdf() {
        return this.pdf;
    }
    
    public void setPdf(byte[] pdf) {
        this.pdf = pdf;
    }
    public byte[] getVideo() {
        return this.video;
    }
    
    public void setVideo(byte[] video) {
        this.video = video;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }




}


