package ec.edu.yavirac.instituto.modelo;
// Generated Sep 14, 2017 9:17:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProyecto;
     private Usuario usuario;
     private String nombre;
     private String descripcion;
     private String lugar;
     private Date fechaIn;
     private Date fechaOut;
     private Integer flag;
     private Set fases = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(Usuario usuario) {
        this.usuario = usuario;
    }
    public Proyecto(Usuario usuario, String nombre, String descripcion, String lugar, Date fechaIn, Date fechaOut, Integer flag, Set fases) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.lugar = lugar;
       this.fechaIn = fechaIn;
       this.fechaOut = fechaOut;
       this.flag = flag;
       this.fases = fases;
    }
   
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Date getFechaIn() {
        return this.fechaIn;
    }
    
    public void setFechaIn(Date fechaIn) {
        this.fechaIn = fechaIn;
    }
    public Date getFechaOut() {
        return this.fechaOut;
    }
    
    public void setFechaOut(Date fechaOut) {
        this.fechaOut = fechaOut;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getFases() {
        return this.fases;
    }
    
    public void setFases(Set fases) {
        this.fases = fases;
    }




}


