package ec.edu.yavirac.instituto.modelo;
// Generated Sep 14, 2017 9:17:28 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer idUsuario;
    private String username;
    private String password;
    private String nombres;
    private String apellidos;
    private String cedula;
    private String movil;
    private String email;
    private String rol;
    private Integer flag;
    private Set evidencias = new HashSet(0);
    private Set proyectos = new HashSet(0);
    private Set asistencias = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String username, String password, String nombres, String apellidos, String cedula, String movil, String email, String rol, Integer flag, Set evidencias, Set proyectos, Set asistencias) {
        this.username = username;
        this.password = password;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.cedula = cedula;
        this.movil = movil;
        this.email = email;
        this.rol = rol;
        this.flag = flag;
        this.evidencias = evidencias;
        this.proyectos = proyectos;
        this.asistencias = asistencias;
    }

    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username.toUpperCase();
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = getHash(password, "MD5");
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres.toUpperCase();
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos.toUpperCase();
    }

    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getMovil() {
        return this.movil;
    }

    public void setMovil(String movil) {
        this.movil = movil;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRol() {
        return this.rol;
    }

    public void setRol(String rol) {
        this.rol = rol;
    }

    public Integer getFlag() {
        return this.flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public Set getEvidencias() {
        return this.evidencias;
    }

    public void setEvidencias(Set evidencias) {
        this.evidencias = evidencias;
    }

    public Set getProyectos() {
        return this.proyectos;
    }

    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }

    public Set getAsistencias() {
        return this.asistencias;
    }

    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }

    public static String getHash(String txt, String hashType) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest
                    .getInstance(hashType);
            byte[] array = md.digest(txt.getBytes());
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < array.length; ++i) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100)
                        .substring(1, 3));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            System.out.println(e.getMessage());
        }
        return null;
    }

}
